Repository codeit-bootcamp-frontend/9-Sprint-Mission, pull requests merged in 2024-07, with the labels that each got.

#6 [김충오] Sprint1
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  src/icon/sns/ic_facebook.png
  src/icon/sns/ic_instagram.png
  src/icon/sns/ic_twitter.png
  src/icon/sns/ic_youtube.png
  src/img/home/Img_home_01.png
  src/img/home/Img_home_02.png
  src/img/home/Img_home_03.png
  src/img/home/Img_home_bottom.png
  src/img/home/Img_home_top.png
  src/img/logo/Property 1=Variant3.png
  style/color.css
  style/global.css
  style/home.css
Labels: 매운맛🔥

#7 [홍예림] Sprint1
  basic-style.css
  faq.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/google-icon.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/kakao-icon.png
  image/login.png
  image/logo-big.png
  image/logo.png
  image/logo/Property 1=Typo.png
  image/logo/Property 1=Typo@2x.png
  image/logo/Property 1=Variant3.png
  image/logo/Property 1=Variant3@2x.png
  image/logo/Property 1=Variant3@3x.png
  image/logo/판다 얼굴.png
  image/logo/판다 얼굴@2x.png
  image/logo/판다 얼굴@3x.png
  image/panda-icon.png
  image/visibility_off.png
  image/visibility_on.png
  image/간편로그인/Component 2.png
  image/간편로그인/Component 2@2x.png
  image/간편로그인/Component 3.png
  image/간편로그인/Component 3@2x.png
  image/간편로그인/google.png
  image/간편로그인/kakao.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  style-index.css
  style-login.css
  style-signup.css
Labels: 매운맛🔥

#9 [지혜민] Sprint1
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .vscode/settings.json
  css/style.css
  fonts/Pretendard/Pretendard-Black.woff
  fonts/Pretendard/Pretendard-Bold.woff
  fonts/Pretendard/Pretendard-ExtraBold.woff
  fonts/Pretendard/Pretendard-ExtraLight.woff
  fonts/Pretendard/Pretendard-Light.woff
  fonts/Pretendard/Pretendard-Medium.woff
  fonts/Pretendard/Pretendard-Regular.woff
  fonts/Pretendard/Pretendard-SemiBold.woff
  fonts/Pretendard/Pretendard-Thin.woff
  images/favicon.ico
  images/icon/ic_facebook.svg
  images/icon/ic_instagram.svg
  images/icon/ic_twitter.svg
  images/icon/ic_youtube.svg
  images/img_default.png
  images/img_home_01.png
  images/img_home_02.png
  images/img_home_03.png
  images/img_home_bottom.png
  images/img_home_top.png
  images/img_inquiry_empty.png
  images/img_reply_empty.png
  images/logo.svg
  index.html
  sass/_base.scss
  sass/_reset.scss
  sass/style.scss
Labels: 매운맛🔥

#11 [조서영] Sprint1
  faq.html
  fonts/ROKAF-Sans-Bold.woff
  fonts/ROKAF-Sans-Medium.woff
  icons/ic_facebook.png
  icons/ic_instagram.png
  icons/ic_twitter.png
  icons/ic_youtube.png
  icons/logo.png
  images/Img_home_top.png
  images/mainPage.png
  images/main_bottom_img.png
  images/main_contents01.png
  images/main_contents02.png
  images/main_contents03.png
  index.html
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#12 [선정민] Sprint1
  assets/landing/icon/ic_facebook.png
  assets/landing/icon/ic_instagram.png
  assets/landing/icon/ic_twitter.png
  assets/landing/icon/ic_youtube.png
  assets/landing/img/Img_home_01.png
  assets/landing/img/Img_home_01@2x.png
  assets/landing/img/Img_home_01@3x.png
  assets/landing/img/Img_home_02-1.png
  assets/landing/img/Img_home_02.png
  assets/landing/img/Img_home_02@2x.png
  assets/landing/img/Img_home_03.png
  assets/landing/img/Img_home_03@2x.png
  assets/landing/img/Img_home_03@3x.png
  assets/landing/img/Img_home_bottom.png
  assets/landing/img/Img_home_bottom@2x.png
  assets/landing/img/Img_home_bottom@3x.png
  assets/landing/img/Img_home_top.png
  assets/landing/img/Img_home_top@2x.png
  assets/landing/img/Img_home_top@3x.png
  assets/landing/img/desktop_01.png
  assets/landing/img/desktop_05.png
  assets/landing/img/logo.png
  assets/landing/img/logo@2x.png
  assets/landing/img/logo@3x.png
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#13 [김예지] Sprint1
  .DS_Store
  sprint1/.DS_Store
  sprint1/faq.html
  sprint1/images/comment_img.png
  sprint1/images/content1.png
  sprint1/images/content2.png
  sprint1/images/content3.png
  sprint1/images/facebook.png
  sprint1/images/footer.png
  sprint1/images/instagram.png
  sprint1/images/logo.png
  sprint1/images/main_section.png
  sprint1/images/sprint1_김예지.png
  sprint1/images/twitter.png
  sprint1/images/youtube.png
  sprint1/index.html
  sprint1/items.html
  sprint1/login.html
  sprint1/privacy.html
  sprint1/style.css
Labels: 매운맛🔥

#14 [구민지] Sprint1
  faq.html
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  index.html
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#4 [박문균]Sprint1
  README.md
  faq.html
  images/Google.png
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/Kakaotalk.png
  images/Mission1.png
  images/eye.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  index.html
  items.html
  privacy.html
  style.css
Labels: 순한맛🐑

#5 [정준영] Sprint1
  .DS_Store
  README.md
  faq.html
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_bottom@2x.png
  img/Img_home_bottom@3x.png
  img/Img_home_top.png
  img/Img_home_top@2x.png
  img/Img_home_top@3x.png
  img/fullheart1.png
  img/fullheart2.png
  img/fullheart3.png
  img/heart1.png
  img/heart2.png
  img/heart3.png
  img/ic_facebook.svg
  img/ic_instagram.svg
  img/ic_twitter.svg
  img/ic_youtube.svg
  img/logo.png
  img/logoMini.png
  index.html
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#15 [정우영] Sprint1
  assets/FAQ.png
  assets/Img_home_01.png
  assets/Img_home_02.png
  assets/Img_home_03.png
  assets/Img_home_bottom.png
  assets/Img_home_top.png
  assets/Privacy Policy.png
  assets/bottom_text.png
  assets/btn_large.png
  assets/codeit - 2024.png
  assets/ic_facebook.png
  assets/ic_instagram.png
  assets/ic_twitter.png
  assets/ic_youtube.png
  assets/logo.png
  assets/popular_text.png
  assets/regist_text.png
  assets/search_text.png
  assets/watch_text.png
  assets/wooy-panda-market.netlify.app_.png
  index.css
  index.html
Labels: 순한맛🐑

#16 [전상민] sprint1
  README.md
  home/home_01.png
  home/home_02.png
  home/home_03.png
  home/home_bottom.png
  home/home_top.png
  index.html
  login.html
  login/login_password.png
  logo/logo_facebook.png
  logo/logo_google.png
  logo/logo_instagram.png
  logo/logo_kakaotalk.png
  logo/logo_panda.png
  logo/logo_twitter.png
  logo/logo_youtube.png
  signup.html
  style.css
  style_login.css
  style_signup.css
Labels: 매운맛🔥

#17 [이재서]sprint1
  .DS_Store
  faq/.DS_Store
  faq/index.html
  home/bottom-banner-image.png
  home/feature1-image.png
  home/feature2-image.png
  home/feature3-image.png
  home/hero-image.png
  icon/ic_facebook.png
  icon/ic_instagram.png
  icon/ic_twitter.png
  icon/ic_youtube.png
  index.html
  items/.DS_Store
  items/index.html
  login/index.html
  login/style.css
  logo/favicon.ico
  logo/panda-market-logo.png
  privacy/.DS_Store
  privacy/index.html
  social/facebook-logo.svg
  social/instagram-logo.svg
  social/twitter-logo.svg
  social/youtube-logo.svg
  style.css
Labels: 매운맛🔥

#19 [김미소] Sprint1
  button-home1.png
  button-login.png
  icon-facebook.png
  icon-insta.png
  icon-twitter.png
  icon-youtube.png
  img-home1.png
  img-home2.png
  img-home3.png
  img-panda1.png
  img-panda2.png
  index.html
  property-logo1.png
  property-logo2.png
  style.css
Labels: 매운맛🔥

#20 [박재열] Sprint1
  icon/ic_facebook.png
  icon/ic_instagram.png
  icon/ic_twitter.png
  icon/ic_youtube.png
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/login_btn.png
  img/logo.png
  index.html
  items.html
  login.html
  style.css
Labels: 매운맛🔥

#21 [박상욱] sprint1
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/ic_facebook.svg
  images/ic_instagram.svg
  images/ic_twitter.svg
  images/ic_youtube.svg
  images/logo.png
  images/mobile_logo.png
  images/panda_market_screenshot.png
  index.html
  style.css
Labels: 순한맛🐑

#23 [김민준] sprint1
  .github/test.txt.txt
  11일.txt
  Frame 2608833.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Property 1=Variant3.png
  facebook.png
  img_default.png
  instagram.png
  main.css
  sprint1.html
  twitter.png
  youtube.png
Labels: 매운맛🔥

#25 [김원]Sprint1
  css/panda.css
  faq.html
  img/footer/ic_facebook.png
  img/footer/ic_instagram.png
  img/footer/ic_twitter.png
  img/footer/ic_youtube.png
  img/header/login.png
  img/header/panda.png
  img/landing/Img_home_01.png
  img/landing/Img_home_02.png
  img/landing/Img_home_03.png
  img/landing/Img_home_bottom.png
  img/landing/Img_home_top.png
  img/landing/btn_large.png
  index.html
  items.html
  login.html
  privacy.html
  readme.md
Labels: 미완성🫠

#26 [김진] Sprint1
  images/Img_home_01.png
  images/Img_home_01@2x.png
  images/Img_home_01@3x.png
  images/Img_home_02-1.png
  images/Img_home_02.png
  images/Img_home_02@2x.png
  images/Img_home_03.png
  images/Img_home_03@2x.png
  images/Img_home_03@3x.png
  images/Img_home_bottom.png
  images/Img_home_bottom@2x.png
  images/Img_home_bottom@3x.png
  images/Img_home_top.png
  images/Img_home_top@2x.png
  images/Img_home_top@3x.png
  images/Img_reply_empty.png
  images/Img_reply_empty.svg
  images/Img_reply_empty@2x.png
  images/Img_reply_empty@3x.png
  images/Property 1=Variant3.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/img/landing/desktop_01.png
  images/img_default.png
  images/img_default.svg
  images/img_default@2x.png
  images/img_default@3x.png
  index.html
  main.css
Labels: 순한맛🐑

#29 [김진] sprint2
  basic.css
  images/Component 2.png
  images/Component 3.png
  images/Frame 7.png
  images/btn_visibility_off_24px.png
  images/btn_visibility_on_24px.png
  images/google.png
  images/판다 얼굴.png
  images/판다마켓.png
  index.html
  login/login.css
  login/login.html
  main.css
  public/color.css
  register/signup.css
  register/signup.html
Labels: 순한맛🐑

#30 [지혜민] sprint2
  .gitignore
  css/style.css
  images/icon/close_eyes.svg
  images/icon/login_google.svg
  images/icon/login_kakao.svg
  images/logo_mobile.svg
  images/panda_market.png
  index.html
  login.html
  sass/_base.scss
  sass/style.scss
  signup.html
Labels: 매운맛🔥

#32 [김미소] Sprint2
  .gitignore
  faq.html
  images/home/button-home1.png
  images/home/button-login.png
  images/home/img-home1.png
  images/home/img-home2.png
  images/home/img-home3.png
  images/home/img-panda1.png
  images/home/img-panda2.png
  images/logo/favicon.png
  images/logo/icon-eye.png
  images/logo/property-logo1.png
  images/logo/property-logo2.png
  images/social/icon-facebook.png
  images/social/icon-google.png
  images/social/icon-insta.png
  images/social/icon-kakao.png
  images/social/icon-twitter.png
  images/social/icon-youtube.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/global.css
  styles/home.css
  styles/login.css
  styles/signup.css
Labels: 매운맛🔥

#34 [박문균] Sprint2
  README.md
  css/login.css
  css/reset.css
  css/signup.css
  css/style.css
  images/login.png
  images/logo.png
  images/logo.svg
  images/signup.png
  index.html
  login.html
  signup.html
Labels: 순한맛🐑

#27 [정준영]Sprint2
  .DS_Store
  README.md
  img/google.png
  img/icon/GoogleBg.png
  img/kakao.png
  img/logo3x.png
  img/visibliity.png
  img/판다마켓.png
  index.html
  login.css
  login.html
  reset.css
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#39 [정우영] sprint2
  assets/FAQ.png
  assets/Img_home_01.png
  assets/Img_home_02.png
  assets/Img_home_03.png
  assets/Img_home_bottom.png
  assets/Img_home_top.png
  assets/Privacy Policy.png
  assets/bottom_text.png
  assets/btn_large.png
  assets/codeit - 2024.png
  assets/ic_facebook.png
  assets/ic_instagram.png
  assets/ic_twitter.png
  assets/ic_youtube.png
  assets/logo.png
  assets/popular_text.png
  assets/regist_text.png
  assets/search_text.png
  assets/watch_text.png
  assets/wooy-panda-market.netlify.app_.png
  faq.html
  images/form/btn-visibility-off.png
  images/form/btn-visibility-on.png
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/google-logo.svg
  images/social/instagram-logo.svg
  images/social/kakao-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.css
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/index.css
  styles/login.css
  styles/reset.css
  styles/signup.css
Labels: 순한맛🐑

#41 [전상민] sprint2
  README.md
  index.html
  login.html
  reset.css
  signup.html
  style.css
  style_login.css
  style_signup.css
Labels: 매운맛🔥

#37 [홍예림] sprint3
  basic-style.css
  index.html
  login.html
  signup.html
  style-index.css
  style-login.css
  style-signup.css
Labels: 미완성🫠

#38 [박상욱] sprint2
  fonts/ROKAF Sans Bold.ttf
  fonts/ROKAF Sans Medium.ttf
  images/btn_visibility_on_24px.png
  images/ic_google.png
  images/ic_kakaotalk.png
  images/logo_login_page.png
  images/onlylogo.png
  index.html
  login.html
  loginstyle.css
  signup.html
  style.css
Labels: 매운맛🔥

#43 [김민준] sprint2
  11일.txt
  faq.html
  img/Frame 2608833.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/Property 1=Variant3.png
  img/Property 1=lg.png
  img/eye.png
  img/facebook.png
  img/gogle.png
  img/img_default.png
  img/instagram.png
  img/kakao.png
  img/twitter.png
  img/youtube.png
  index.html
  items.html
  login.css
  login.html
  main.css
  privacy.html
  signup.html
  sprint1.html
Labels: 매운맛🔥

#46 [문창기] sprint 3
  README.md
  css/global.css
  css/login-signup.css
  css/loginPage.css
  css/mainPage.css
  images/loginPage_mobile.png
  images/loginPage_tablet.png
  images/mainPage_mobile.png
  images/mainPage_tablet.png
  images/signUpPage_mobile.png
  images/signUpPage_tablet.png
  index.html
  login.html
  signup.html
Labels: 순한맛🐑

#47 [조서영] Sprint3
  font_color.css
  images/meta_tag.png
  index.html
  login.css
  login.html
  signup.html
  style.css
Labels: 매운맛🔥

#48 [구민지] Sprint3
  faq.html
  images/icon/ic_facebook.svg
  images/icon/ic_instagram.svg
  images/icon/ic_twitter.svg
  images/icon/ic_youtube.svg
  images/thumbnail.png
  index.html
  login.html
  signup.html
  style.css
  style/auth.css
  style/global.css
  style/index.css
Labels: 매운맛🔥

#55 [박문균] sprint3
  README.md
  css/login.css
  css/reset.css
  css/signup.css
  css/style.css
  images/Mission1.png
  images/eye.png
  images/eye.svg
  images/index_375.png
  images/login.png
  images/login_375.png
  images/meta-img.svg
  images/signup.png
  images/signup_375.png
  index.html
  login.html
  login.js
  signup.html
Labels: 순한맛🐑

#59 [정우영] sprint3
  .vscode/settings.json
  index.html
  login.html
  signup.html
  styles/index.css
  styles/login.css
  styles/reset.css
  styles/signup.css
Labels: 순한맛🐑

#57 [전상민] sprint3
  .vscode/settings.json
  README/README.md
  css/login_singup.css
  css/reset.css
  css/style.css
  index.html
  login.html
  reset.css
  signup.html
  style_signup.css
Labels: 매운맛🔥

#49 [김예지] sprint3
  .DS_Store
  faq.html
  images/.DS_Store
  images/banner_section.png
  images/content1.png
  images/content2.png
  images/content3.png
  images/footer.png
  images/icons/eye-invisible.svg
  images/icons/eye-visible.svg
  images/logo/facebook.png
  images/logo/favicon.ico
  images/logo/google.png
  images/logo/instagram.png
  images/logo/kakao.png
  images/logo/login_logo.svg
  images/logo/logo.svg
  images/logo/mobile_logo.svg
  images/logo/twitter.png
  images/logo/youtube.png
  index.html
  items.html
  privacy.html
  signin.html
  signup.html
  sprint1/.DS_Store
  sprint1/images/comment_img.png
  sprint1/images/logo.png
  sprint1/images/sprint1_김예지.png
  sprint1/index.html
  sprint1/login.html
  sprint1/privacy.html
  sprint1/style.css
  sprint2/faq.html
  sprint2/images/banner_section.png
  sprint2/images/content1.png
  sprint2/images/content2.png
  sprint2/images/content3.png
  sprint2/images/footer.png
  sprint2/images/logo/facebook.png
  sprint2/images/logo/instagram.png
  sprint2/images/logo/twitter.png
  sprint2/images/logo/youtube.png
  sprint2/items.html
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#53 [지혜민] sprint3
  css/style.css
  images/icon/open_eyes.svg
  js/login.js
  js/signup.js
  login.html
  sass/style.scss
  signup.html
Labels: 매운맛🔥

#54 [박상욱] sprint3
  index.html
  login.html
  signup.html
  style.css
Labels: 미완성🫠

#56 [김충오] sprint3
  index.html
  login.html
  signup.html
  src/img/logo/metaTagImg.png
  style/home.css
  style/login.css
Labels: 매운맛🔥

#58 [이재서] sprint3
  .DS_Store
  .gitignore
  css/glober.css
  css/login-signup.css
  css/main.css
  faq/.DS_Store
  index.html
  items/.DS_Store
  login.html
  login/index.html
  privacy/.DS_Store
  signup.html
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#60 [김원] sprint3
  images/icons/eye-invisible.svg
  images/icons/eye-visible.svg
  images/logo/logo.svg
  index.html
  login.html
  signup.html
  styles/auth.css
  styles/global.css
  styles/home.css
  styles/login.css
  styles/signup.css
Labels: 미완성🫠

#62 [선정민] Sprint3
  common.css
  index.html
  login.css
  login.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥
